### ISSUE TITLE
Shutting down sandboxes may hang

### ISSUE THREAD

**Issue by manuelstein** [knix-microfunctions/knix#105]
When sandboxes are terminated along with the other services, they don't shutdown.
It seems the issue is related to the Thrift client not being able to contact the datalayer anymore:
```
1615983259.380000,1615983259380,"2021-03-17 12:14:19.380","INFO","org.microfunctions.sandbox.frontend","Server is shutting down..."
1615983259.381000,1615983259381,"2021-03-17 12:14:19.381","INFO","org.microfunctions.sandbox.frontend","producer: stopping ..."
1615983259.381000,1615983259381,"2021-03-17 12:14:19.381","INFO","org.microfunctions.sandbox.frontend","producer: stopped"
1615983259.385000,1615983259385286,"INFO","ip-10-10-2-87.eu-central-1.compute.internal","wf-knix-786e01191e5d8564c9e4b93f827b2915-00001-deployment-n7zmn","0l","sand@sand","test_wf","786e01191e5d8564c9e4b93f827b2915","test","2021-03-17 12:14:19.385","[FunctionWorker] Done"
1615983259.381000,1615983259381,"2021-03-17 12:14:19.381","INFO","org.microfunctions.sandbox.frontend","consumer: stopping ..."
1615983269.009000,1615983269009,"2021-03-17 12:14:29.009","INFO","org.microfunctions.sandbox.frontend","consumer: stopped"
1615983269.009000,1615983269009,"2021-03-17 12:14:29.009","INFO","org.microfunctions.sandbox.frontend","datalayer: stopping ..."
1615983269.009000,1615983269009,"2021-03-17 12:14:29.009","INFO","org.microfunctions.sandbox.frontend","datalayer: stopped"
1615983269.009000,1615983269009,"2021-03-17 12:14:29.009","INFO","org.microfunctions.sandbox.frontend","Frontend stopped"
[2021-03-17 12:15:08,989] [INFO] Shutting down the queue service...
[2021-03-17 12:15:08,989] [INFO] Terminating queue service: pid: 10...
[2021-03-17 12:15:08,997] [INFO] Shutting down fluent-bit...
[2021-03-17 12:15:10,999] [INFO] Terminating fluent-bit: pid: 7...
[2021-03-17 12:15:11,000] [INFO] Shutdown complete.
failed to resolve sockaddr for dl-knix-2.datalayer:4998
Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 408, in run
    self._get_and_handle_message()
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 118, in _get_and_handle_message
    lqm = self._local_queue_client.getMessage(self._instructions_topic, POLL_TIMEOUT)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/LocalQueueClient.py", line 78, in getMessage
    lqm = self.queue.getAndRemoveMessage(topic, timeout)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 208, in getAndRemoveMessage
    return self.recv_getAndRemoveMessage()
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 221, in recv_getAndRemoveMessage
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 334, in readMessageBegin
    proto_id = self.__readUByte()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 313, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 283, in read
    self.readFrame()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 287, in readFrame
    buff = self.__trans.readAll(4)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 126, in read
    buff = self.handle.recv(sz)
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 223, in sigterm
    raise KeyboardInterrupt
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/DataLayerClient.py", line 210, in putMapEntry
    status = self.datalayer.putEntryToMap(self.keyspace, self.maptablename, mapname, row, loc)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1907, in putEntryToMap
    self.send_putEntryToMap(keyspace, table, mapName, keyValuePair, locality)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1920, in send_putEntryToMap
    self._oprot.trans.flush()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 304, in flush
    self.__trans.write(buf)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 149, in write
    message='Transport not open')
thrift.transport.TTransport.TTransportException: Transport not open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 99, in open
    addrs = self._resolveAddr()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 42, in _resolveAddr
    socket.AI_PASSIVE | socket.AI_ADDRCONFIG)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
failed to resolve sockaddr for dl-knix-2.datalayer:4998
Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 408, in run
    self._get_and_handle_message()
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 118, in _get_and_handle_message
    lqm = self._local_queue_client.getMessage(self._instructions_topic, POLL_TIMEOUT)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/LocalQueueClient.py", line 78, in getMessage
    lqm = self.queue.getAndRemoveMessage(topic, timeout)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 208, in getAndRemoveMessage
    return self.recv_getAndRemoveMessage()
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 221, in recv_getAndRemoveMessage
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 334, in readMessageBegin
    proto_id = self.__readUByte()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 313, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 283, in read
    self.readFrame()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 287, in readFrame
    buff = self.__trans.readAll(4)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 126, in read
    buff = self.handle.recv(sz)
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 223, in sigterm
    raise KeyboardInterrupt
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/DataLayerClient.py", line 210, in putMapEntry
    status = self.datalayer.putEntryToMap(self.keyspace, self.maptablename, mapname, row, loc)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1907, in putEntryToMap
    self.send_putEntryToMap(keyspace, table, mapName, keyValuePair, locality)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1920, in send_putEntryToMap
    self._oprot.trans.flush()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 304, in flush
    self.__trans.write(buf)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 149, in write
    message='Transport not open')
thrift.transport.TTransport.TTransportException: Transport not open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 99, in open
    addrs = self._resolveAddr()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 42, in _resolveAddr
    socket.AI_PASSIVE | socket.AI_ADDRCONFIG)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
failed to resolve sockaddr for dl-knix-2.datalayer:4998
Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 408, in run
    self._get_and_handle_message()
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 118, in _get_and_handle_message
    lqm = self._local_queue_client.getMessage(self._instructions_topic, POLL_TIMEOUT)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/LocalQueueClient.py", line 78, in getMessage
    lqm = self.queue.getAndRemoveMessage(topic, timeout)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 208, in getAndRemoveMessage
    return self.recv_getAndRemoveMessage()
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 221, in recv_getAndRemoveMessage
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 334, in readMessageBegin
    proto_id = self.__readUByte()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 313, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 283, in read
    self.readFrame()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 287, in readFrame
    buff = self.__trans.readAll(4)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 126, in read
    buff = self.handle.recv(sz)
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 223, in sigterm
    raise KeyboardInterrupt
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/DataLayerClient.py", line 210, in putMapEntry
    status = self.datalayer.putEntryToMap(self.keyspace, self.maptablename, mapname, row, loc)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1907, in putEntryToMap
    self.send_putEntryToMap(keyspace, table, mapName, keyValuePair, locality)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1920, in send_putEntryToMap
    self._oprot.trans.flush()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 304, in flush
    self.__trans.write(buf)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 149, in write
    message='Transport not open')
thrift.transport.TTransport.TTransportException: Transport not open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 99, in open
    addrs = self._resolveAddr()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 42, in _resolveAddr
    socket.AI_PASSIVE | socket.AI_ADDRCONFIG)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
failed to resolve sockaddr for dl-knix-2.datalayer:4998
Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 408, in run
    self._get_and_handle_message()
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 118, in _get_and_handle_message
    lqm = self._local_queue_client.getMessage(self._instructions_topic, POLL_TIMEOUT)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/LocalQueueClient.py", line 78, in getMessage
    lqm = self.queue.getAndRemoveMessage(topic, timeout)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 208, in getAndRemoveMessage
    return self.recv_getAndRemoveMessage()
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 221, in recv_getAndRemoveMessage
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 334, in readMessageBegin
    proto_id = self.__readUByte()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 313, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 283, in read
    self.readFrame()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 287, in readFrame
    buff = self.__trans.readAll(4)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 126, in read
    buff = self.handle.recv(sz)
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 223, in sigterm
    raise KeyboardInterrupt
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/DataLayerClient.py", line 210, in putMapEntry
    status = self.datalayer.putEntryToMap(self.keyspace, self.maptablename, mapname, row, loc)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1907, in putEntryToMap
    self.send_putEntryToMap(keyspace, table, mapName, keyValuePair, locality)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1920, in send_putEntryToMap
    self._oprot.trans.flush()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 304, in flush
    self.__trans.write(buf)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 149, in write
    message='Transport not open')
thrift.transport.TTransport.TTransportException: Transport not open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 99, in open
    addrs = self._resolveAddr()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 42, in _resolveAddr
    socket.AI_PASSIVE | socket.AI_ADDRCONFIG)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
failed to resolve sockaddr for dl-knix-2.datalayer:4998
Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 408, in run
    self._get_and_handle_message()
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 118, in _get_and_handle_message
    lqm = self._local_queue_client.getMessage(self._instructions_topic, POLL_TIMEOUT)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/LocalQueueClient.py", line 78, in getMessage
    lqm = self.queue.getAndRemoveMessage(topic, timeout)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 208, in getAndRemoveMessage
    return self.recv_getAndRemoveMessage()
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 221, in recv_getAndRemoveMessage
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 334, in readMessageBegin
    proto_id = self.__readUByte()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 313, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 283, in read
    self.readFrame()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 287, in readFrame
    buff = self.__trans.readAll(4)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 126, in read
    buff = self.handle.recv(sz)
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 223, in sigterm
    raise KeyboardInterrupt
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/DataLayerClient.py", line 210, in putMapEntry
    status = self.datalayer.putEntryToMap(self.keyspace, self.maptablename, mapname, row, loc)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1907, in putEntryToMap
    self.send_putEntryToMap(keyspace, table, mapName, keyValuePair, locality)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1920, in send_putEntryToMap
    self._oprot.trans.flush()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 304, in flush
    self.__trans.write(buf)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 149, in write
    message='Transport not open')
thrift.transport.TTransport.TTransportException: Transport not open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 99, in open
    addrs = self._resolveAddr()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 42, in _resolveAddr
    socket.AI_PASSIVE | socket.AI_ADDRCONFIG)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
failed to resolve sockaddr for dl-knix-2.datalayer:4998
Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 408, in run
    self._get_and_handle_message()
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 118, in _get_and_handle_message
    lqm = self._local_queue_client.getMessage(self._instructions_topic, POLL_TIMEOUT)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/LocalQueueClient.py", line 78, in getMessage
    lqm = self.queue.getAndRemoveMessage(topic, timeout)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 208, in getAndRemoveMessage
    return self.recv_getAndRemoveMessage()
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 221, in recv_getAndRemoveMessage
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 334, in readMessageBegin
    proto_id = self.__readUByte()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 313, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 283, in read
    self.readFrame()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 287, in readFrame
    buff = self.__trans.readAll(4)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 126, in read
    buff = self.handle.recv(sz)
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 223, in sigterm
    raise KeyboardInterrupt
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/DataLayerClient.py", line 210, in putMapEntry
    status = self.datalayer.putEntryToMap(self.keyspace, self.maptablename, mapname, row, loc)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1907, in putEntryToMap
    self.send_putEntryToMap(keyspace, table, mapName, keyValuePair, locality)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1920, in send_putEntryToMap
    self._oprot.trans.flush()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 304, in flush
    self.__trans.write(buf)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 149, in write
    message='Transport not open')
thrift.transport.TTransport.TTransportException: Transport not open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 99, in open
    addrs = self._resolveAddr()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 42, in _resolveAddr
    socket.AI_PASSIVE | socket.AI_ADDRCONFIG)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
failed to resolve sockaddr for dl-knix-2.datalayer:4998
Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 408, in run
    self._get_and_handle_message()
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 118, in _get_and_handle_message
    lqm = self._local_queue_client.getMessage(self._instructions_topic, POLL_TIMEOUT)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/LocalQueueClient.py", line 78, in getMessage
    lqm = self.queue.getAndRemoveMessage(topic, timeout)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 208, in getAndRemoveMessage
    return self.recv_getAndRemoveMessage()
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/local_queue/service/LocalQueueService.py", line 221, in recv_getAndRemoveMessage
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 334, in readMessageBegin
    proto_id = self.__readUByte()
  File "/usr/local/lib/python3.6/dist-packages/thrift/protocol/TCompactProtocol.py", line 313, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 283, in read
    self.readFrame()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 287, in readFrame
    buff = self.__trans.readAll(4)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 126, in read
    buff = self.handle.recv(sz)
  File "/opt/mfn/SandboxAgent/sandboxagent.py", line 223, in sigterm
    raise KeyboardInterrupt
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/DataLayerClient.py", line 210, in putMapEntry
    status = self.datalayer.putEntryToMap(self.keyspace, self.maptablename, mapname, row, loc)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1907, in putEntryToMap
    self.send_putEntryToMap(keyspace, table, mapName, keyValuePair, locality)
  File "/opt/mfn/SandboxAgent/../FunctionWorker/python/data_layer/service/DataLayerService.py", line 1920, in send_putEntryToMap
    self._oprot.trans.flush()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TTransport.py", line 304, in flush
    self.__trans.write(buf)
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 149, in write
    message='Transport not open')
thrift.transport.TTransport.TTransportException: Transport not open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 99, in open
    addrs = self._resolveAddr()
  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/TSocket.py", line 42, in _resolveAddr
    socket.AI_PASSIVE | socket.AI_ADDRCONFIG)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by iakkus** [comment]
It starts with the LocalQueue exception. Basically, the sandbox shutdown shuts down the queue at some point, but that should be the last process to shut down.

Besides that, when the components are shutting down, are the workflows undeployed first? If not, these errors will happen and the sandbox will be eventually shut down. But I guess they will keep gettig restarted, because the underlying K8s has not been told about the shutdown? Is that the problem?

**Comment by iakkus** [comment]
Is this resolved by commit [f5f059f3b705d8743bad4627b5da5df940601586](https://github.com/knix-microfunctions/knix/commit/f5f059f3b705d8743bad4627b5da5df940601586)?

**Comment by iakkus** [comment]
This commit may be reated to resolving this issue: https://github.com/knix-microfunctions/knix/commit/c277126fb9199ea428a1581aa86721190ac8574f

**Comment by iakkus** [comment]
Another commit that handles shutdowns more properly: https://github.com/knix-microfunctions/knix/commit/c05b4902eeb6fb724aede707864220f4cd706d61

**Comment by iakkus** [comment]
This issue only manifests itself during the uninstallation of the entire platform. The above commits should alleviate this problem. If it persists, please reopen.
