### ISSUE TITLE
Upgrading KNIX breaks the datalayer

### ISSUE THREAD

**Issue by manuelstein** [knix-microfunctions/knix#106]
We've recently used helm upgrade resulting in a datalayer failure leaving all DL nodes inoperable.

`helm upgrade <rel> <chart>` updates, among others, the statefulsets for riak and datalayer.

1) In a tight setup with 3 nodes, one riak node going down means not sufficient nodes are available or replication. So right after a DL starting, there were a couple of 
``` log
[1616081830822] [2021-03-18 15:37:10.822] [ERROR] [org.microfunctions.data_layer.RiakAccess] selectAllKeysWithType() failed.  Keyspace: __MFn_Keyspaces__  Table: null  TableType: default
java.util.concurrent.ExecutionException: com.basho.riak.client.core.netty.RiakResponseException: insufficient_vnodes_available
        at com.basho.riak.client.core.FutureOperation.throwExceptionIfSet(FutureOperation.java:329) ~[datalayerservice.jar:?]
        at com.basho.riak.client.core.FutureOperation.get(FutureOperation.java:315) ~[datalayerservice.jar:?]
        at com.basho.riak.client.api.commands.CoreFutureAdapter.get(CoreFutureAdapter.java:52) ~[datalayerservice.jar:?]
        at com.basho.riak.client.api.RiakCommand.execute(RiakCommand.java:93) ~[datalayerservice.jar:?]
        at com.basho.riak.client.api.RiakClient.execute(RiakClient.java:355) ~[datalayerservice.jar:?]
```

2) Riak nodes are resolved by their IP address ___before___ the DL svc is started. This is a problem as during upgrade, Riak nodes will/may start with new IP addresses. While the riak cluster formation scripts had already been rewritten to use FQDNs for the nodes to find each other, the DL code is using IPv4 address objects and needs a bit of rework to use FQDN with the riak client library. After upgrade, it was not able to recover due to the pre-resolved IP addresses:
```
[1616083831524] [2021-03-18 16:10:31.524] [ERROR] [com.basho.riak.client.core.RiakNode] RiakNode failed healthcheck operation; 10.10.1.87:8087 com.basho.riak.client.core.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.1.87:8087
[1616083835586] [2021-03-18 16:10:35.586] [ERROR] [com.basho.riak.client.core.RiakNode] Connection attempt failed: 10.10.0.138:8087; io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.0.138:8087
[1616083835586] [2021-03-18 16:10:35.586] [ERROR] [com.basho.riak.client.core.RiakNode] RiakNode failed healthcheck operation; 10.10.0.138:8087 com.basho.riak.client.core.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.0.138:8087
[1616083837668] [2021-03-18 16:10:37.668] [ERROR] [com.basho.riak.client.core.RiakNode] Connection attempt failed: 10.10.1.87:8087; io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.1.87:8087
[1616083837668] [2021-03-18 16:10:37.668] [ERROR] [com.basho.riak.client.core.RiakNode] RiakNode failed healthcheck operation; 10.10.1.87:8087 com.basho.riak.client.core.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.1.87:8087
[1616083840738] [2021-03-18 16:10:40.738] [ERROR] [com.basho.riak.client.core.RiakNode] Connection attempt failed: 10.10.0.138:8087; io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.0.138:8087
[1616083840738] [2021-03-18 16:10:40.738] [ERROR] [com.basho.riak.client.core.RiakNode] RiakNode failed healthcheck operation; 10.10.0.138:8087 com.basho.riak.client.core.ConnectionFailedException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.0.138:8087
```

**Comment by manuelstein** [comment]
fixed in PR #107
